# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTMainView.ui'
#
# Created by: PyQt6 UI code generator
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        # 修改点：PyQt6 中枚举类型需要完整的命名空间
        Dialog.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Dialog.resize(1217, 792)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 10, 531, 771))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.open_file = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.open_file.setObjectName("open_file")
        self.gridLayout.addWidget(self.open_file, 0, 2, 1, 1)
        self.file_text = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.file_text.setObjectName("file_text")
        self.gridLayout.addWidget(self.file_text, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.output = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 3)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(620, 500, 531, 281))
        self.textBrowser.setObjectName("textBrowser")
        self.pdf_to_word = QtWidgets.QPushButton(Dialog)
        self.pdf_to_word.setGeometry(QtCore.QRect(630, 30, 141, 41))
        self.pdf_to_word.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"gridline-color: rgb(0, 85, 255);")
        self.pdf_to_word.setObjectName("pdf_to_word")
        self.doc_to_docx = QtWidgets.QPushButton(Dialog)
        self.doc_to_docx.setGeometry(QtCore.QRect(820, 30, 141, 41))
        self.doc_to_docx.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"gridline-color: rgb(0, 85, 255);")
        self.doc_to_docx.setObjectName("doc_to_docx")
        self.ok = QtWidgets.QPushButton(Dialog)
        self.ok.setGeometry(QtCore.QRect(990, 200, 146, 61))
        self.ok.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"gridline-color: rgb(0, 85, 255);")
        self.ok.setObjectName("ok")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(630, 90, 331, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.input_key = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.input_key.setObjectName("input_key")
        self.verticalLayout_2.addWidget(self.input_key)
        self.clear_output = QtWidgets.QPushButton(Dialog)
        self.clear_output.setGeometry(QtCore.QRect(1020, 30, 141, 41))
        self.clear_output.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"gridline-color: rgb(0, 85, 255);")
        self.clear_output.setObjectName("clear_output")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "自动word汇总工具(小云)"))
        self.open_file.setText(_translate("Dialog", "选择目录"))
        self.label.setText(_translate("Dialog", "输入文件目录:"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">1.pdf转word:支持将输出文件目录的所有pdf文件批量转换为word</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">2.word格式转换:将doc格式转为docx,如果后面要使用自动汇总功能必须先要点击这个按钮运行转换</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ff0000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">3.首先选择word文件所在目录,然后点击右边对应的功能</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ff0000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">4.提取字段那个地方就是要从word表格里面提取的表头信息，比如姓名,学号啥的，每个字段之间用英文逗号分割</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ff0000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">5.文件会保存到对应文件目录的output目录下面</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ff0000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">开发者:小云(qq:3483421977)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ff0000;\"><br /></p></body></html>"))
        self.pdf_to_word.setText(_translate("Dialog", "批量pdf转word"))
        self.doc_to_docx.setText(_translate("Dialog", "word格式转换"))
        self.ok.setText(_translate("Dialog", "自动汇总word报名表"))
        self.label_2.setText(_translate("Dialog", "要提取的word表格字段:"))
        self.clear_output.setText(_translate("Dialog", "清除输出"))
